### ISSUE TITLE
debug deduced type?

### ISSUE THREAD

**Issue by ehuhtala** [asutton/clang#36]
Would it be possible to output what a deduced type looks like? 

E.g. for lambda, I'm thinking something like:

auto f = [f=4](char){};
using f_type = std::decay<decltype(f)>::type;

constexpr {
    compiler.debug($f_type);
}

Or for templates:

template <typename T>
void func() {
    constexpr {
        compiler.debug($T);
    }
}

**Comment by asutton** [comment]
Fixed in the injection-2 branch.

**Comment by ehuhtala** [comment]
Works very well for the first case, thanks :)

Can the constexpr {} block be inside class/function scopes? or just global scope? e.g. the template example still doesn't work due to:

blah.cpp:102:5: error: expression is not an integral constant expression
    constexpr {
    ^
blah.cpp:102:5: note: non-literal type '(lambda at blah.cpp:102:5)' cannot be used in a constant expression

**Comment by ehuhtala** [comment]
Looks like the error is specific to templated functions/classes. If they are non-templated, the constexpr{} block works as I'm expecting.

**Comment by ehuhtala** [comment]
in template classes, the error looks like:
`blah.cpp:15:5: error: expression is not an integral constant expression
    constexpr {
    ^
blah.cpp:16:9: note: non-literal type '<dependent type>' cannot be used in a constant expression
        compiler.debug($T);
        ^
note: in call to '__constexpr_decl()'`
